import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import '../data/quiz_catalog.dart';
import '../models/learning_models.dart';
import '../state/app_controller.dart';
import '../theme/app_theme.dart';

class QuickChallengeScreen extends StatefulWidget {
  const QuickChallengeScreen({required this.controller, required this.count, this.timed = false, super.key});
  final AppController controller; final int count; final bool timed;
  @override State<QuickChallengeScreen> createState() => _QuickChallengeScreenState();
}
class _QuickChallengeScreenState extends State<QuickChallengeScreen> {
  late final List<QuizQuestion> _questions; int _index=0,_score=0,_seconds=20; Timer? _timer; bool _locked=false; int? _selected;
  @override void initState(){super.initState(); final all=[...QuizCatalog.questions]..shuffle(Random()); _questions=all.take(widget.count).toList(); if(widget.timed)_startTimer();}
  void _startTimer(){_timer?.cancel();_seconds=20;_timer=Timer.periodic(const Duration(seconds:1),(t){if(!mounted||_locked)return;setState(()=>_seconds--);if(_seconds<=0)_answer(-1);});}
  void _answer(int index){if(_locked)return;setState((){_locked=true;_selected=index;if(index==_questions[_index].correctIndex)_score++;});if(widget.timed)_timer?.cancel();}
  Future<void> _next() async{if(!_locked)return;if(_index==_questions.length-1){_timer?.cancel();final reward=widget.timed?await widget.controller.recordTimedChallenge(correct:_score,total:_questions.length,completed:true):await widget.controller.recordQuickChallenge(correct:_score,total:_questions.length);if(!mounted)return;await showDialog<void>(context:context,barrierDismissible:false,builder:(_)=>_VictoryDialog(score:_score,total:_questions.length,reward:reward,timed:widget.timed));if(mounted)Navigator.of(context).pop();return;}setState((){_index++;_selected=null;_locked=false;});if(widget.timed)_startTimer();}
  @override void dispose(){_timer?.cancel();super.dispose();}
  @override Widget build(BuildContext context){final q=_questions[_index];return Scaffold(appBar:AppBar(title:Text(widget.timed?'⚡ Sprint cartographique':'🎲 Mode rapide')),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,110),children:[Row(children:[Text('${_index+1}/${_questions.length}',style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.burgundy)),const Spacer(),Row(children:List.generate(3,(i)=>Icon(i<widget.controller.lives?Icons.favorite_rounded:Icons.favorite_border_rounded,color:AppColors.coral,size:18)))]),const SizedBox(height:10),LinearProgressIndicator(value:(_index+1)/_questions.length,minHeight:8),if(widget.timed)...[const SizedBox(height:12),Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_seconds<=5?const Color(0xFFFFE7EC):AppColors.softRose,borderRadius:BorderRadius.circular(14)),child:Row(children:[Icon(Icons.timer_rounded,color:_seconds<=5?AppColors.red:AppColors.burgundy),const SizedBox(width:7),Text('$_seconds s',style:TextStyle(fontWeight:FontWeight.w900,color:_seconds<=5?AppColors.red:AppColors.burgundy)),const Spacer(),const Text('Pas le temps de négocier avec le GPS 😄',style:TextStyle(fontSize:10))]))],const SizedBox(height:22),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.ink,AppColors.burgundy]),borderRadius:BorderRadius.circular(26)),child:Text(q.question,style:const TextStyle(color:Colors.white,fontSize:21,height:1.3,fontWeight:FontWeight.w800))),const SizedBox(height:16),for(var i=0;i<q.options.length;i++)...[_Option(index:i,label:q.options[i],selected:_selected==i,correct:_locked&&i==q.correctIndex,wrong:_locked&&_selected==i&&i!=q.correctIndex,onTap:()=>_answer(i)),const SizedBox(height:10)],if(_locked)Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:AppColors.softRose,borderRadius:BorderRadius.circular(18)),child:Text(q.explanation,style:const TextStyle(height:1.4,fontWeight:FontWeight.w600)))])),bottomNavigationBar:SafeArea(minimum:const EdgeInsets.fromLTRB(16,8,16,14),child:FilledButton.icon(onPressed:_locked?_next:null,icon:const Icon(Icons.arrow_forward_rounded),label:Text(_index==_questions.length-1?'Réclamer mes XP':'Suivant'))));}
}
class _Option extends StatelessWidget{const _Option({required this.index,required this.label,required this.selected,required this.correct,required this.wrong,required this.onTap});final int index;final String label;final bool selected,correct,wrong;final VoidCallback onTap;@override Widget build(BuildContext context){final border=correct?AppColors.success:wrong?AppColors.red:selected?AppColors.burgundy:const Color(0xFFE9DCE1);return Material(color:correct?const Color(0xFFE6F7EF):wrong?const Color(0xFFFFE8ED):Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18),side:BorderSide(color:border,width:correct||wrong?1.7:1)),child:InkWell(onTap:selected||correct||wrong?null:onTap,borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[CircleAvatar(radius:18,backgroundColor:border.withValues(alpha:.14),foregroundColor:border,child:Text(String.fromCharCode(65+index),style:const TextStyle(fontWeight:FontWeight.w900))),const SizedBox(width:13),Expanded(child:Text(label,style:const TextStyle(fontWeight:FontWeight.w600,height:1.3))),if(correct)const Icon(Icons.check_circle_rounded,color:AppColors.success),if(wrong)const Icon(Icons.cancel_rounded,color:AppColors.red)]))));}}
class _VictoryDialog extends StatelessWidget{const _VictoryDialog({required this.score,required this.total,required this.reward,required this.timed});final int score,total,reward;final bool timed;@override Widget build(BuildContext context){final pct=((score/total)*100).round();final emoji=pct==100?'🏆':pct>=70?'🥳':pct>=50?'😎':'🗺️';return AlertDialog(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(28)),content:Column(mainAxisSize:MainAxisSize.min,children:[TweenAnimationBuilder<double>(tween:Tween(begin:.4,end:1),duration:const Duration(milliseconds:550),curve:Curves.elasticOut,builder:(_,v,child)=>Transform.scale(scale:v,child:child),child:Text(emoji,style:const TextStyle(fontSize:64))),const SizedBox(height:8),Text(timed?'Sprint terminé !':'Mission express terminée !',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('$score/$total • $pct%',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)),const SizedBox(height:12),Text('+$reward XP 🎉',style:const TextStyle(color:AppColors.burgundy,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(pct==100?'Même le satellite est impressionné. 🛰️':'Chaque bonne réponse vous rapproche du niveau suivant !',textAlign:TextAlign.center),const SizedBox(height:18),FilledButton(onPressed:()=>Navigator.of(context).pop(),child:const Text('Cool, je continue !'))]));}}
